[package]
name = "cryptoconditions"
version = "0.1.0"
authors = ["Scott Sadler <me@scottsadler.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cryptoconditions"       
#crate-type = ["rlib", "dylib"]
crate-type = ["cdylib"]

[dependencies]
asn1 = { git = "https://github.com/alex/rust-asn1" }
libsecp256k1 = "0.2.2"
simple_asn1 = { git = "https://github.com/ssadler/simple_asn1" }
num-bigint = "0.2.6"
num-traits = "0.2"
sha2 = "0.8.0"
wasm-bindgen = "0.2"
js-sys = "0.3"
cfg-if = "0.1"
log = "0.4"
console_log = { version = "0.2", optional = true }
base64 = "*"
hex = "*"
file = "*"

[dev-dependencies]
rustc-hex = "2"
serde_json = "1.0"

[features]
default = ["console_log"]
